config/routes.rb
Larsblog::Application.routes.draw do 

 

  resources :shows

  devise_for :users

  mount Ckeditor::Engine => '/ckeditor'
  
  resources :posts do
    resources :comments
    

  end
  
  
  match 'login88' => 'posts#login'
  match 'user/sign_out' => 'user#sign_out'

  root :to => "posts#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title, :username
  has_many :comments
  validates_presence_of :title, :username , :message => "Ahhhh!"
  paginates_per 5

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  authorize_resource
  @posts_title       = 'Member Login'
@posts_description = 'Member login page.'
@posts_keywords    = 'Site, Login, Members'
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.page(params[:page])
    @shows = Show.all

    respond_to do |format|
      format.html  #index.html.erb
      format.json { render json: @posts }
      format.atom
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    unauthorized! if cannot? :manage, @post

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    unauthorized! if cannot? :manage, @post
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    unauthorized! if cannot? :manage, @post

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: 'Erfolg!' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end

    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    unauthorized! if cannot? :manage, @post

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    unauthorized! if cannot? :manage, @post

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    
  
    end

  def role?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
   end

   
   @posts = Post.all(:select => "title", :order => "posted_at DESC", :limit => 20) 

    respond_to do |format|
    format.rss { render :layout => false }
    
   end

  
  end
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/views/posts/_form.html.erb
<% set_meta_tags :noindex => true %>
 <meta name="robots" content="noindex" />
<% set_meta_tags :noindex => 'googlebot' %>
 <meta name="googlebot" content="noindex" />
  <% if user_signed_in? %>
<%= semantic_form_for @post, :html => { :class => '' } do |f| %>
    <%= f.input :title, :label => false, :input_html =>{:class => "span9"} %>
    <%= f.input :body, :label => false, :input_html =>{:class => "span9"}, :as => :ckeditor %>
    
      <%= f.input :username,  :label => false, :input_html => {:class => "input-mini uneditable-input", :value => current_user.username} , :as => :hidden %>

   

    
      
        <%= f.actions do %>
          <%= f.action  :submit,  :label =>"Anlegen" %>
          <%= f.action :cancel, :label => 'Zurück' %>
        <% end %>

      

      
    
<% end %>
          <% else %>
          404 :)

<% end %>

app/views/posts/_post.html.erb
<%= div_for post do %>
  <h1 id="link"><%= link_to(post.title,post) %></h1>
  
  <%=  raw(post.body) %>
  <div class="row">
    <span class="created_at span9">
      <%= link_to(post.comments.count.to_s + ' Kommentare      ',"/posts/#{post.id.to_s}#Kom" ) %>&nbsp;&nbsp;&nbsp;
        <%= post.created_at.to_s(:long) %>
        <%= 'von ' + post.username.to_s %>

       
      

    </span>
  </div>
<% end %>

app/views/posts/edit.html.erb
<% set_meta_tags :noindex => true %>
# <meta name="robots" content="noindex" />
<% set_meta_tags :noindex => 'googlebot' %>
# <meta name="googlebot" content="noindex" />
<%- model_class = @post.class -%>

<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<h1><% title 'Lieutenant! Lieutenant!' %></h1>
<%= render @posts %>
 
 <%= content_for :infos do %>
   
  <% end %>

  <% content_for :shows do %>
    <h2 style="text-align: center;" >
      Shows <br />
    </h2>
    <%= render @shows %>


  <% end %>


<%= content_for :adminlinks do %>
  <li>
    <div style="text-align: center;" >
      ADMINBAR!
    </div>
    <%= link_to('Neuer Post',
            new_post_path) %>
  </li>
  <% if user_signed_in? %>
  <li>
   <div>Angemeldet als <%= current_user.username %>  </div>
  <%= link_to('Logout', destroy_user_session_path, :method => :get) %>        
  </li>

  <% end %>

<% end %>
<%= paginate @posts %>

app/views/posts/login.html.erb
<% set_meta_tags :noindex => true %>
# <meta name="robots" content="noindex" />
<% set_meta_tags :noindex => 'googlebot' %>
# <meta name="googlebot" content="noindex" />
 <% if can? :read, @post %>  
<div style="margin-top: 50px; text-align: center; " >
<%= form_for("user", :url => user_session_path) do |f| %>
<table  >
<tr  >
  <td >Name</td>
  <td >Passwort</td>
  <td><%= f.label :remember_me %></td>
</tr> 
<tr >
  <td ><%= f.text_field :username %></td>
  <td><%= f.password_field :password %></td>
  <td><%= f.check_box :remember_me %>
  </td>
</tr>  
</table>

  
  <%= f.submit 'Sign in' %>
  
<% end %>
</div>
<% end %>

app/views/posts/new.html.erb
<% set_meta_tags :noindex => true %>
# <meta name="robots" content="noindex" />
<% set_meta_tags :noindex => 'googlebot' %>
# <meta name="googlebot" content="noindex" />
<%- model_class = @post.class -%>

  

<%= render :partial => 'form' %>

app/views/posts/new_info.html.erb
<% set_meta_tags :noindex => true %>
# <meta name="robots" content="noindex" />
<% set_meta_tags :noindex => 'googlebot' %>
# <meta name="googlebot" content="noindex" />
<%- model_class = @post.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%- model_class = @post.class -%>

<h1 style="text-align: center; margin-top: 50px;"><%= @post.title %></h1>

  <div style="margin-top: 50px;">
    <%=  raw(@post.body) %>
  </div>
   <%= link_to ('Zurück'),
              posts_path, :class => 'btn'  %>
  <% if can? :manage, @post %>  
    <%= link_to ('Editieren'),
              edit_post_path(@post), :class => 'btn' %>
  <% end %>
  <% if can? :manage, @post %> 
  <%= link_to ('Löschen'),
              post_path(@post),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
  <% end %>
  <% set_meta_tags :keywords => truncate(@post.body, :length => 255 ) %>
  <% set_meta_tags :title => @post.title %>
  <% if @post.comments.count >= 5 %>
  <h2 style="margin-top: 50px;"><a name="Kom"></a>
    <a href="#Kom2">Kommentar schreiben</a></h2>
  <% end %>

<% @post.comments.each do |comment| %>
  <p style="margin-top: 50px;">
    <b>Name:</b>
    <%= comment.name %>
  </p>
 
  <p>
    <b></b>
    <%= simple_format(comment.body) %>
  </p>
  <p style="text-align: right;">
    <b ></b>
    <%= comment.created_at.to_s(:long) %>
  </p>
  <% if can? :manage, @comments %>
    <%= link_to 'Löschen', post_comment_path(@post, comment), confirm: 'Are you sure?', method: :delete ,
              :class => 'btn btn-danger btn-mini' %>
    <% end %>
  

  <% end %>

<div class="form-actions">
 
  
<%= semantic_form_for([@post, @post.comments.build]) do |f| %>
   
  <div style="margin-top: 50px;" >
    <h2><a name="Kom2"></a></h2>
    <br />
  
    
    
    
    <%= f.input :name , :label => false, :input_html => {:placeholder =>"Just write your name, dummy!"}  %>
      
    <%= f.input :mail , :label => false, :input_html => {:placeholder =>"Your@Mail.com"} %>
    

 
    <%= f.input :body, :label => false, :input_html => {:placeholder =>"For your health!"} %>
  </div>
  
    <%= f.actions %>
  
</div>
<% end %>