config/routes.rb
Larsblog::Application.routes.draw do 

 

  resources :shows

  devise_for :users

  mount Ckeditor::Engine => '/ckeditor'
  
  resources :posts do
    resources :comments
    

  end
  
  
  match 'login88' => 'posts#login'
  match 'user/sign_out' => 'user#sign_out'

  root :to => "posts#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Lieutenant! Lieutenant!" %></title>
    <%= csrf_meta_tags %>
    <link rel="alternate" type="application/atom+xml" title="Lieutenant!" href="<%= posts_path(:atom) %>">
    <%= display_meta_tags :site => 'Lieutenant! Lieutenant!' %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->


    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "ckeditor/init" %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>
   
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Lieutenant! Lieutenant!</a>
          <div class="container nav-collapse" style="text-align: right;">
            <ul class="nav pull-center" >
              <div class="pull-right">
             
               
                 <a href="http://www.facebook.com/LieutenantLieutenant" rel="nofollow" target="_blank">
              <%= image_tag 'fb.jpg' %>

              </a>
             
             <%= link_to( image_tag('rss2.jpg'), posts_path(:atom)) %>
           

            </div>
              
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="span9 well" style="margin-left: -1px; padding-right: 7px; margin-right: -16px; background-color: #FBFAFF; padding-left: 7px; ">
          
          <img width ="940px" src =  "http://www.imgbox.de/users/public/images/d7LXUW7cVj.jpg">
        
          <div style=" word-wrap: normal ;">
            <%= display_meta_tags %>

            
            <%= yield %>
            

          </div>
        </div><!--/span-->
        <div class="span3">
          <div  style="background-color: white;" >
           
              <%= yield :infos %>
              <% begin %>
                 <script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>
<div class="well">
<script> 
new TWTR.Widget({
  version: 2,
  type: 'profile',
  rpp: 4,
  interval: 30000,
  width: 'auto',
  height: 300,
  theme: {
    shell: {
      background: '#F5F5F5',
      color: 'black'
    },
    tweets: {
      background: '#F5F5F5',
      color: 'black',
      links: 'blue'
    }
  },
  features: {
    scrollbar: false,
    loop: false,
    live: true,
    behavior: 'all'
  }
}).render().setUser('LieutenantBand').start();
</script>
</div>
<div class="well">
<iframe width="auto" height="295" style="position: relative; left: 39px; display: block; width: 150px; height: 295px; text-align: center;" src="http://bandcamp.com/EmbeddedPlayer/v=2/album=232232556/size=tall/bgcol=F5F5F5/linkcol=4285BB/" allowtransparency="true" frameborder="0"><a href="http://lieutenants.bandcamp.com/album/demo">Demo by Lieutenant! Lieutenant!</a></iframe>
</div>



              <% rescue Exception=> message %>
              <% message %>
              <% end %>
          
          </div>  
          <div class="well">
            <%= yield :shows %><br />
             <% if can? :manage, @shows %>
              <%= link_to 'Neue Show', new_show_path %><br />
              <%= link_to 'Löschen / Editieren', shows_path %>
            <% end %>

          </div>  

          <% if user_signed_in? %>
          <div class="well">
            <ul class="unstyled">
              <%= yield :adminlinks %>
            </ul>
          </div>
          <% end %>
        </div>
      </div><!--/row--> 
    </div> <!-- /container --> 
          

      

    



  </body>
</html>